language: go

env: GO111MODULE=on

deploy:

  provider: heroku

  api_key:

    secure: "jMAWvEZY1EmmUd8iFPxRSip4VtxkZ7iCBIdlZKdvq6sKUejzV/yvk3XwwTi08x9zU0OEIpxTrbs6KIYxnMGVrPPTlXuZUMxJT1HT0iX0lR6gdT33+BU60uwJfOEgx3SDvZ20K6xET4mmCgYxFl9wpbksnoxOfRukfFDvc0IscMqauMUSZf/TKEKlC1g1VVCLGfAYo9CXZZi4usn9UlZ716pbJ0cDv+YOAK/y3BPrOJThypXuLs/kOH16oeP9ZOJNoeJzjYA+I4F+I8jNayTa7qVjbIlYTUw7AYlP9bpsr8Z8AsnSPaVC/xi1muAfHlrj9ih9EG9pd/O9y8hzvLjgkKa1wXpWDss3IVRSKyXyaCEh0lYQAonm49DMQ4eaCu/TSH5NEvAtqUc8HV8PIesWGThVHpsjmc24+hZul+mUBk56txgyvkFE4px7qrsZneOVULOQ1AsMyeZGqBuFSJsVe6VLz1PpxHTRM/1m9DR7hQNHqqBrtfTRWldKZAPRAcJYuWKyru9tdu2viEonfXrGY+CN8vH0mZkUx1SvLHGl4ha1a38OO/5bYmNLrg+ct2Ejuxfm3FGHNjOmNjX57883mpnIVn7FXQw6TIXO+A0mIBOcURuUPUxf27ZdS5lEKZFmEKaxOmzpc3bPvUQBzmDcu3Yzn8LTsbtBs59VYEmojt0="

  app: datos2-actividad1

addons:

  sonarcloud:

    organization: "nachogranados"

    token:

      secure: "NwBOSC/fPAQ7SAfxYbYQsXpOaMcH2tEHPKuAGyf3PEObk4y6uAnlILtMD8cuNx5JomH/qHcc9cZNOzJtj8JqR/7izc8/56S9qA1HHTQuYZHJB5mLZVTP0Y/51u8hSjOsIBVr217fcVnL11zwrTDxJ4P6Cnq9qYCBJ3qbZnsnOnf+IlUOv1kq+CGTPcg/bKVWwUpPezsNHEizbmxGi80XHIXW7oXHj/tvrdsJoppn7s03TUGv5V9bz5rxpR6bFsbjrPLViwAXJkH/KI3aFNc6U0koqVcohGkl5xzm7ZkMqVGyXJHBz8gOoqxqFO7Eitid/WYkjTrKoTM38AAD57fcyPpsEux75Bc+ZxDZBx+MlBrWiLSN+290P/ssZ8L/dyFgalzmSji+Fx8FEP8TRNMJRoUImzBLIOmW74hb3ioN15bL6fYTyLOcVbTHjH2faxAdA6RjxJCfQOCyw3wWgvYHVswjWuvrwdsYoWCNDih/McCSnYTpF2/If28K17RPlVrlzQpT6SPUHdbnPms7/6ZltkpyXVSqE2hUROfUsuyrOhPJFdg8VCGZhyXg9jlhS25dnig1OQgzqGdyswuz//ROCC40QA1B/0+pq4/Dz6hFQbPFAQ72do6VgYy7ntKmL8CJ+mPESXC4sYmEISjAAe4bFIK4aNUXPKLa5TdoXLwDBKo="

git:

  depth: false

script:

  - sonar-scanner













